{
    "athan_1": {
        "audio_id": "athan_1",
        "desc": "Mishary Al Afasy Kuwait",
        "length": "2m34s",
        "name": "Athan 1",
        "type": "athan",
    },
    "athan_2": {
        "audio_id": "athan_2",
        "desc": "Mohamed Tarek",
        "length": "2m30s",
        "name": "Athan 2",
        "type": "athan",
    },
    "athan_3": {
        "audio_id": "athan_3",
        "desc": "Ameen Ka3sees Algeria",
        "length": "3m4s",
        "name": "Athan 3",
        "type": "athan",
    },
    "athan_4": {
        "audio_id": "athan_4",
        "desc": "Nasser Al Qattami KSA",
        "length": "2m7s",
        "name": "Athan 4",
        "type": "athan",
    },
    "athan_5": {
        "audio_id": "athan_5",
        "desc": "Bosnia",
        "length": "2m49s",
        "name": "Athan 5",
        "type": "athan",
    },
    "athan_6": {
        "audio_id": "athan_6",
        "desc": "Mohammed Al Amin Oman",
        "length": "3m24s",
        "name": "Athan 6",
        "type": "athan",
    },
    "athan_fajr_1": {
        "audio_id": "athan_fajr_1",
        "desc": "Mohammad Al-Amin Mosque Beirut",
        "length": "2m37s",
        "name": "Athan Fajr 1",
        "type": "fajr",
    },
    "takbir_1": {
        "audio_id": "takbir_1",
        "desc": "Nasir Al-Qatami KSA",
        "length": "10s",
        "name": "Takbir 1",
        "type": "takbir",
    },
    "tweet": {
        "audio_id": "tweet",
        "desc": "Tweet",
        "length": "1s",
        "name": "Tweet",
        "type": "notification",
    },
}
